### ISSUE TITLE
User list pagination issue

### ISSUE THREAD

**Issue by alexmerlin** [dotkernel/admin#32]
The total count found in background call /user/list/ is always equal to 1, no matter how many items are there to be displayed. Because of this, bootstrap displays only one page of items and no links for the rest of the pages.
`{"total":**1**,"rows":[...]}`

**Comment by gabidj** [comment]
Thanks for posting this issue.

The equal to 1 issue is caused by a `group by` statement, which affects the `count()` statement.

This bug was fixed and it is scheduled for the admin 1.0.1 release
